/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        earth: {
          50: '#FAF7F2',
          100: '#F5EFE6',
          200: '#EDE4D5',
          300: '#DDD0BD',
          400: '#B8A58D',
          500: '#8E7A63',
          700: '#574D3F',
          800: '#383127',
          900: '#241E17',
          950: '#17130F',
        },
        terracotta: {
          50: '#FDF4F2',
          100: '#FDEEE9',
          200: '#F9D0C5',
          300: '#F2A997',
          400: '#EA7A5C',
          500: '#E2725B',
          600: '#D9654D',
          700: '#B54832',
          800: '#873322',
        },
        sage: {
          50: '#F4F8F5',
          100: '#EAF3ED',
          200: '#D4E7DC',
          300: '#A9CBB8',
          400: '#75A98B',
          500: '#3F7253',
          600: '#2D5A43',
          700: '#224432',
          800: '#183124',
        },
        teal: {
          50: '#F0F8F8',
          100: '#E0F2F1',
          200: '#B2DFDB',
          400: '#4DB6AC',
          500: '#2A7575',
          600: '#1E5A5A',
          700: '#154242',
        },
        amber: {
          50: '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          400: '#FBBF24',
          500: '#D97706',
          600: '#B45309',
        },
        purple: {
          50: '#FAF5FF',
          100: '#F5F3FF',
          200: '#E9D5FF',
          400: '#A78BFA',
          500: '#7C3AED',
          600: '#6D28D9',
        },
        forest: {
          950: '#021510',
          900: '#042b1d',
          800: '#063B28',
          700: '#056B3A',
          600: '#0a8a4f',
          500: '#10b36a',
        },
        gold: {
          50: '#fff9e8',
          100: '#FFF4D6',
          200: '#ffe566',
          300: '#FFD21A',
          400: '#e8b800',
          500: '#c79a00',
        },
        pink: {
          400: '#ff3d99',
          500: '#F5007A',
          600: '#cc0066',
        },
        cream: {
          100: '#fff9e8',
          200: '#FFF4D6',
          300: '#f5e6c0',
        },
      },
      // ONE family for the whole product. Every legacy alias (font-serif,
      // font-mono, font-display) resolves to Manrope so no screen can drift
      // back into a second typeface.
      fontFamily: {
        display: ['"Manrope"', '"Noto Sans Devanagari"', 'system-ui', 'sans-serif'],
        serif: ['"Manrope"', '"Noto Sans Devanagari"', 'system-ui', 'sans-serif'],
        sans: ['"Manrope"', '"Noto Sans Devanagari"', 'system-ui', 'sans-serif'],
        mono: ['"Manrope"', '"Noto Sans Devanagari"', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.85' },
          '50%': { transform: 'scale(1.04)', opacity: '1' },
        },
        spinSlow: {
          to: { transform: 'rotate(360deg)' },
        },
        spinReverse: {
          to: { transform: 'rotate(-360deg)' },
        },
        floatY: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        drift: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '33%': { transform: 'translate(8px, -10px)' },
          '66%': { transform: 'translate(-6px, 8px)' },
        },
        pulseRing: {
          '0%': { transform: 'scale(0.8)', opacity: '0.7' },
          '100%': { transform: 'scale(2.4)', opacity: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        hintSlide: {
          '0%': { transform: 'translateX(0)', opacity: '0.4' },
          '50%': { transform: 'translateX(14px)', opacity: '1' },
          '100%': { transform: 'translateX(0)', opacity: '0.4' },
        },
        twinkle: {
          '0%, 100%': { opacity: '0.2' },
          '50%': { opacity: '0.9' },
        },
        starDrift: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '25%': { transform: 'translate(4px, -6px)' },
          '50%': { transform: 'translate(-3px, 4px)' },
          '75%': { transform: 'translate(5px, 2px)' },
        },
        meteor: {
          '0%': { transform: 'translate(0, 0) rotate(35deg)', opacity: '0' },
          '3%': { opacity: '0.9' },
          '15%': { transform: 'translate(-180px, 126px) rotate(35deg)', opacity: '0' },
          '100%': { transform: 'translate(-180px, 126px) rotate(35deg)', opacity: '0' },
        },
        sway1: {
          '0%, 100%': { transform: 'rotate(-1.5deg)' },
          '50%': { transform: 'rotate(1.5deg)' },
        },
        sway2: {
          '0%, 100%': { transform: 'rotate(1deg)' },
          '50%': { transform: 'rotate(-2deg)' },
        },
        sway3: {
          '0%, 100%': { transform: 'rotate(-0.8deg)' },
          '50%': { transform: 'rotate(1.2deg)' },
        },
        sway4: {
          '0%, 100%': { transform: 'rotate(0.6deg)' },
          '50%': { transform: 'rotate(-1.4deg)' },
        },
        waveBar: {
          '0%, 100%': { transform: 'scaleY(0.3)' },
          '50%': { transform: 'scaleY(1)' },
        },
        mapPulse: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.4)' },
        },
        mapGlow: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        mapBreath: {
          '0%, 100%': { filter: 'drop-shadow(0 0 8px rgba(255,210,26,0.15))' },
          '50%': { filter: 'drop-shadow(0 0 20px rgba(255,210,26,0.3))' },
        },
        statePulse: {
          '0%': { opacity: '0.6', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(1.15)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        breathe: 'breathe 4s ease-in-out infinite',
        'spin-slow': 'spinSlow 28s linear infinite',
        'spin-reverse': 'spinReverse 36s linear infinite',
        'float-y': 'floatY 6s ease-in-out infinite',
        drift: 'drift 14s ease-in-out infinite',
        'pulse-ring': 'pulseRing 2.4s ease-out infinite',
        shimmer: 'shimmer 3s linear infinite',
        'hint-slide': 'hintSlide 2.2s ease-in-out infinite',
        twinkle: 'twinkle 3s ease-in-out infinite',
        'star-drift': 'starDrift 18s ease-in-out infinite',
        meteor: 'meteor 14s ease-in infinite',
        'sway-1': 'sway1 8s ease-in-out infinite',
        'sway-2': 'sway2 11s ease-in-out infinite',
        'sway-3': 'sway3 14s ease-in-out infinite',
        'sway-4': 'sway4 10s ease-in-out infinite',
        'wave-bar': 'waveBar 0.9s ease-in-out infinite',
        'map-pulse': 'mapPulse 3s ease-in-out infinite',
        'map-glow': 'mapGlow 4s ease-in-out infinite',
        'map-breath': 'mapBreath 6s ease-in-out infinite',
        'state-pulse': 'statePulse 1.5s ease-out infinite',
        'fade-in-up': 'fadeInUp 0.6s ease-out both',
      },
    },
  },
  plugins: [],
};
